Feature: update pycc 4
CitrineInformatics/learn-citrination pull request #25
Opened 2018-05-13 18:05 UTC by maxhutch

This is based on #24 by @Setogit , but needs to be opened within the repository in order to access the testing API key.

2018-05-13 23:56 UTC, Setogit commented
Confirmed that this PR works as #24 in my local environment as well as Travis as expected.  Closed my PR #24.

2018-05-15 18:20 UTC, carenac commented on MLonCitrination.ipynb
> +    "print(\"We predict the density of {} to be {} +/- {}\".format(inputs[0]['Chemical formula'], prediction.value, prediction.loss))"
Not a big deal, but do we want to be consistent with design table results here?

`round(prediction.value, 2)`

2018-05-15 18:37 UTC, carenac requested changes

2018-05-15 18:37 UTC, carenac commented on ExperimentalDesign.ipynb
> +    "print(\"We predict the ZT of {} (@ 300K) to be {} +/- {}\".format(inputs[0]['formula'], prediction[0].get_value('Property ZT'), prediction[0].get_value('Property ZT')))\n"
`prediction[0].get_value('Property ZT')`  should have a `.value`

2018-05-15 18:40 UTC, maxhutch commented on MLonCitrination.ipynb
> +    "print(\"We predict the density of {} to be {} +/- {}\".format(inputs[0]['Chemical formula'], prediction.value, prediction.loss))"
The logic in the design results is a little more complicated than that; I'd suggest we leave it as is (its consistent with what it was before).

2018-05-15 18:49 UTC, carenac approved these changes

2018-05-15 19:22 UTC, merged