minor updates; stylistic touch-ups
CitrineInformatics/learn-citrination pull request #35
Opened 2019-07-15 18:36 UTC by enze-chen

No major content updates, other than adding `client.data.delete_dataset()`. Mostly to clean up the code from January to have better readability and flow.

2019-07-15 22:31 UTC, maxhutch commented
The diff here is extensive.  Could you comment on the line changes that are more than stylistic touch-ups?

2019-07-15 23:00 UTC, enze-chen commented
@maxhutch Hmm, 1) Perhaps I used the wrong language, and 2) Perhaps it's a little intimidating, but I actually do think the changes leading to the massive diff, besides the three points I named, are stylistic in nature. I can certainly comment on what those are:
- More direct import of Python packages, e.g. `from time import sleep` instead of `import time`
- Specifying the input keys and arguments,  e.g. 
```python
CitrinationClient(api_key=key, 
                  site=site)
``` 
instead of `CitrinationClient(key, site)`.
- More consistent formatting on code, with inline `backticks` instead of **bold**.
- Adding some descriptive texts around naked code blocks, particularly when they appear consecutively.
- Consistent language / names.
- Displaying more URLs to show how API corresponds to the web interface.
- Removed redundant, dead code. Reworded awkward parts.
- Simplified docstrings and made them more consistent.

2019-07-16 18:01 UTC, enze-chen commented on citrination_api_examples/clients_sequence/1_data_client_api_tutorial.ipynb
> +    "# data_client.delete_dataset(dataset_id=dataset_id)"
Added a block for `client.data.delete_dataset()`. It's commented out so someone doesn't accidentally do this.

2019-07-16 22:24 UTC, enze-chen commented on citrination_api_examples/clients_sequence/4_search_client_api_tutorial.ipynb
> +    "### Example: Filter a range of values\n",
added an exercise to create a `Filter` with `min` and `max`

2019-07-16 22:25 UTC, enze-chen commented on citrination_api_examples/clients_sequence/4_search_client_api_tutorial.ipynb
> +    "### Example: Logic\n",
Added an example with a `Filter` with `logic`.

2019-07-16 22:26 UTC, enze-chen commented on citrination_api_examples/clients_sequence/6_sequential_learning_steel_fatigue.ipynb
> +    "# Sequential Learning Workshop\n",
This SL notebook uses a steel fatigue dataset instead of a toy view.

2019-07-16 22:26 UTC, enze-chen commented on citrination_api_examples/clients_sequence/steel_fatigue_wrapper_class.py
> +Authors: Eddie Kim, Enze Chen, Nils Persson
This is the corresponding wrapper for the steel fatigue SL demo.

2019-07-16 22:27 UTC, enze-chen commented
@maxhutch Added comments where the changes actually took place. Thanks. :)

2019-07-19 22:13 UTC, maxhutch requested changes
The changes look fine, but there is some weird formatting in the github render of:
https://github.com/CitrineInformatics/learn-citrination/blob/update-api-tutorials/citrination_api_examples/clients_sequence/6_sequential_learning_steel_fatigue.ipynb

Do you know what's going on there?

2019-07-19 22:28 UTC, enze-chen commented
> Do you know what's going on there?   

Wow; good catch! That's some leftover HTML formatting that's hidden when the Markdown renders in Jupyter, but apparently not on GitHub! :O I removed all of it—*I think*.

2019-07-20 05:33 UTC, enze-chen commented
Hmm....it looks like there's a library dependency on [`ase`](https://gitlab.com/ase/ase) that suddenly requires Python 3.5+. It's when we try to import `dfttopif`. How should we proceed @maxhutch? Remove Python 2.7 from the support as well?

2026-02-19 12:41 UTC, closed without merging