Suggested edits to TsneDemo
CitrineInformatics/learn-citrination pull request #36
Opened 2019-11-23 18:22 UTC by 1mikegrn

1. refactored graphing protocols to satisfy the depreciation warning; pivoted towards using an ax. protocol for a more OOP graphing approach

2. In cell #5 for coordinates_and_bg, used transpose() on an arrayed list of lists, instead of greating a zero array and populating the array piecewise.

3. Instead of using for loops over print functions, changed the display protocol to use list comprehensions in dictionaries, then pushed the dictionaries into a set of pandas dataframes for better display. Also allows for hiding the URL string in an HTML hyperlink.

4. Added appropriate comments to subsection the jupyter cells for user convenience, and fixed inconsistent naming conventions.

2019-11-23 19:07 UTC, 1mikegrn commented
Obviously the .travis.yml check is going to fail since I'm not providing my personal API key; how would y'all like the CitrinationClient(api_key=?) to be formatted to demonstrate the CI build pass? Notebook works fine locally, I'm just not pushing a personal api_key to GitHub.

2019-12-02 21:02 UTC, ahl389 submitted a review, later dismissed
Sounds good to me. I don't have any familiarity with this project, but I'm happy to see these changes merged if others have deemed them necessary!

2019-12-02 22:43 UTC, maxhutch requested changes
> Obviously the .travis.yml check is going to fail since I'm not providing my personal API key; how would y'all like the CitrinationClient(api_key=?) to be formatted to demonstrate the CI build pass? Notebook works fine locally, I'm just not pushing a personal api_key to GitHub.

The testing harness inserts a valid API key into the environment, so if you change that block back to th way it was, then the tests will pass.  It is a dangerous practice to ever put any API key (or password) in code, which is why we strongly recommend putting it into your environment and loading it using `os.environ`.

2019-12-02 22:43 UTC, maxhutch commented on citrination_api_examples/TsneDemo.ipynb
> +    "    api_key=\"INSERT_PERSONAL_API_KEY\",\n",
```suggestion
    "    api_key=os.environ[\"CITRINATION_API_KEY\"],\n",
```

2019-12-02 22:54 UTC, maxhutch commented
> 1. refactored graphing protocols to satisfy the depreciation warning; pivoted towards using an ax. protocol for a more OOP graphing approach
> 2. In cell #5 for coordinates_and_bg, used transpose() on an arrayed list of lists, instead of greating a zero array and populating the array piecewise.
> 3. Instead of using for loops over print functions, changed the display protocol to use list comprehensions in dictionaries, then pushed the dictionaries into a set of pandas dataframes for better display. Also allows for hiding the URL string in an HTML hyperlink.
> 4. Added appropriate comments to subsection the jupyter cells for user convenience, and fixed inconsistent naming conventions.

These changes are slick!  Assuming the tests pass after you update the client definition block, it should be good to go.

2019-12-03 01:06 UTC, maxhutch commented
https://github.com/CitrineInformatics/learn-citrination/pull/37 will fix the python 2.x failure.  To pickup the API key, we need to move this branch into `CitrineInformatics/learn-citrination` (rather than your fork).  I'm going to create a new target branch for you, do the code review on the way into it, and then open a follow-up PR to get it into `master`.

2019-12-03 15:57 UTC, 1mikegrn commented
Sounds good, just let me know which branch you'd like to pull `1mikegrn/learn-citrination` towards and I'll set up the PR to push into it.

2019-12-03 22:41 UTC, maxhutch approved these changes

2019-12-03 22:42 UTC, maxhutch commented
We expect the tests to pass once the branch is staged.

2019-12-03 22:42 UTC, merged